# Site settings
title: WCTC .NET Database
email: mmcarthey@wctc.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the GitHub Pages site for the WCTC .NET Database course.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wctc-net-database.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from production build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Optional settings
google_analytics: UA-XXXXX-Y # Replace with your Google Analytics tracking ID
twitter_username: exampleorg # Replace with your organization's Twitter username
github_username:  exampleorg # Replace with your organization's GitHub username

# Jekyll theme configuration (for themes supporting this)
minima:
  skin: air # Theme skin can be set if the theme supports different skins

# SEO tags
author: WCTC .NET Database
linkedin:
  username: markmcarthey
