name: Publish Markdown to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'markdown/**/*.md'  # Trigger the workflow only on changes to Markdown files in the markdown directory
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert Markdown into HTML and PDF
      uses: KoharaKazuya/marp-cli-action@v2
      with:
        entryPoint: 'markdown/*.md'  # Adjust to match the markdown directory
        generate-html: true
        generate-pdf: false

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: html  # Ensure this points to the directory where your HTML files are generated