name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert Markdown to HTML
      uses: KoharaKazuya/marp-cli-action@v2
      with:
        args: 'markdown/*.md --html --output ./html'

    - name: Ensure HTML directory exists
      run: mkdir -p html

    - name: List Markdown directory contents
      run: ls -la markdown

    - name: List HTML directory contents
      run: ls -la html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAGES_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages
        allow_empty_commit: false
        keep_files: false
        force_orphan: false
        enable_jekyll: false
        disable_nojekyll: false
        exclude_assets: .github